type Icons = {
  [key: string]: any;
};

export const icons: Icons = {
  Emotions: require("@/assets/imgs/emotions/happy.png"),
  Food: require("@/assets/imgs/foods/hamburger.png"),
  Fruit: require("@/assets/imgs/foods/fruits/apple.png"),
  Vegetable: require("@/assets/imgs/foods/vegetables/zani.png"),
  Dessert: require("@/assets/imgs/foods/desserts/shortcake.png"),
  Utensils: require("@/assets/imgs/foods/utensils/fork.png"),
  Clothing: require("@/assets/imgs/clothing/t-shirt.png"),
  Colors: require("@/assets/imgs/colors/rainbow2.png"),
  Shapes: require("@/assets/imgs/shapes/circle2.png"),
  Transportation: require("@/assets/imgs/transportation/car.png"),
  Weather: require("@/assets/imgs/weather/sunny.png"),
  Body: require("@/assets/imgs/body/body.png"),
  Hobbies: require("@/assets/imgs/hobbies/reading.png"),
  Holidays: require("@/assets/imgs/holidays/holiday.png"),
  Animals: require("@/assets/imgs/animals/pet/dog2.png"),
  Bird: require("@/assets/imgs/animals/bird/bird.png"),
  Bug: require("@/assets/imgs/animals/bug/beetle.png"),
  Farm: require("@/assets/imgs/animals/farm/cow.png"),
  Forest: require("@/assets/imgs/animals/forest/fox.png"),
  Jungle: require("@/assets/imgs/animals/jungle/monkey.png"),
  Mythological: require("@/assets/imgs/animals/mythological/dragon.png"),
  Water: require("@/assets/imgs/animals/ocean-water/fish.png"),
  Other: require("@/assets/imgs/animals/other/bat.png"),
  Pet: require("@/assets/imgs/animals/pet/cat.png"),
  Prehistoric: require("@/assets/imgs/animals/prehistoric/t-rex.png"),
  Reptile: require("@/assets/imgs/animals/reptile-amphibian/snake.png"),
  Directions: require("@/assets/imgs/directions/compass.png"),
  Places: require("@/assets/imgs/places/globe.png"),
  Occupations: require("@/assets/imgs/occupations/male/astronaut.png"),
  School: require("@/assets/imgs/places/school.png"),
  Bathroom: require("@/assets/imgs/bathroom/bathtub.png"),
};
